### ISSUE TITLE
Backtest queue issue

### ISSUE THREAD

**Issue by djdeathdj** [msei99/pbgui#27]
error fetching ticks b string indices must be integers {'code': -1003, 'msg': 'Way too many requests; IP(xxx) banned until 1705673011099. Please use the websocket for live updates to avoid bans.'}

When several backtests of one pair are launched simultaneously, the statistics server is bombarded with hundreds of requests simultaneously and blocks the address. Maybe you should first download the required history in pairs and then run a bunch of tests?

**Comment by msei99** [comment]
Set number of CPU to a lower number.
