### ISSUE TITLE
Run Optimizer stops immediately

### ISSUE THREAD

**Issue by sunhotblaze** [msei99/pbgui#56]
`using numba
using numba
using numba
using numba
fetching market_specific_settings for APEUSDT...

market_type                                 futures
user                                        okx_01
latency_simulation_ms                       1000
starting_balance                            1000.0
start_date                                  2023-05-25
end_date                                    2024-05-25
slim_analysis                               True
base_dir                                    /root/passivbot/backtests/pbgui
ohlcv                                       True
adg_n_subdivisions                          10
enable_interactive_plot                     False
plot_theme                                  light
plot_candles_interval                       1m
spot                                        False
exchange                                    okx
session_name                                2023-05-25_2024-05-25
symbol                                      APEUSDT
caches_dirpath                              /root/passivbot/backtests/pbgui/okx/APEUSDT/caches/
plots_dirpath                               /root/passivbot/backtests/pbgui/okx/APEUSDT/plots/
c_mult                                      0.1
hedge_mode                                  True
inverse                                     False
maker_fee                                   0.0002
min_cost                                    0.0
min_qty                                     1.0
price_step                                  0.0001
qty_step                                    1.0
taker_fee                                   0.0005
n_harmonies                                 32
hm_considering_rate                         0.9
bandwidth                                   0.07
pitch_adjusting_rate                        0.24
n_particles                                 36
w                                           0.73
c0                                          1
c1                                          0.4
algorithm                                   harmony_search
n_cpus                                      2
iters                                       4000
n_backtest_slices                           5
maximum_drawdown_max_long                   0.25
maximum_drawdown_max_short                  0.25
maximum_drawdown_1pct_worst_mean_long       0.1
maximum_drawdown_1pct_worst_mean_short      0.1
maximum_pa_distance_std_long                -1
maximum_pa_distance_std_short               -1
maximum_pa_distance_mean_long               -1
maximum_pa_distance_mean_short              -1
maximum_pa_distance_1pct_worst_mean_long    -0.1
maximum_pa_distance_1pct_worst_mean_short   -0.1
maximum_loss_profit_ratio_long              0.15
maximum_loss_profit_ratio_short             0.15
maximum_hrs_stuck_max_long                  120
maximum_hrs_stuck_max_short                 120
maximum_exposure_ratios_mean_long           -1
maximum_exposure_ratios_mean_short          -1
maximum_time_at_max_exposure_long           -1
maximum_time_at_max_exposure_short          -1
clip_threshold                              0
do_long                                     True
do_short                                    True
backwards_tp_long                           True
backwards_tp_short                          True
passivbot_mode                              recursive_grid
results_fpath                               results_harmony_search_recursive_grid/2024-05-25T09-53-07_APEUSDT/
config_name                                 recursive_grid_test
logging_level                               0

starting new initial eval 1 of 32 
starting new initial eval 2 of 32`

I tried running the optimizer many times and immediately stopped afterwards. This is the log file

**Comment by sunhotblaze** [comment]
![1](https://github.com/msei99/pbgui/assets/30214897/85447c6a-2426-4a5e-a277-eca97d651030)

When I use Single instances and click on the Activate ALL command line, the following message appears:

![Uploading 2.PNG…]()

**Comment by sunhotblaze** [comment]
![1](https://github.com/msei99/pbgui/assets/30214897/7e56238f-ce92-43c3-8eba-4c2af7096c08)

When I use Single instances and click on the Activate ALL command line, the following message appears:

![2](https://github.com/msei99/pbgui/assets/30214897/82ce60d7-8578-4330-a771-465796f4b70b)

**Comment by msei99** [comment]
> starting new initial eval 1 of 32 starting new initial eval 2 of 32`
> 
> I tried running the optimizer many times and immediately stopped afterwards. This is the log file

How much memory do you have. OPtimizer needs at least 16 GB of RAM and for some coins with long history, it needs more than 16GB. Best is 32GB RAM.

**Comment by msei99** [comment]
> ![1](https://private-user-images.githubusercontent.com/30214897/333852347-7e56238f-ce92-43c3-8eba-4c2af7096c08.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTgyMTAsIm5iZiI6MTcxNjgxNzkxMCwicGF0aCI6Ii8zMDIxNDg5Ny8zMzM4NTIzNDctN2U1NjIzOGYtY2U5Mi00M2MzLThlYmEtNGMyYWY3MDk2YzA4LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEzNTE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNzg2NTFiYWMzMmI4NzRiMWRhMGE5MjUyMGMxZGJhOWY4ZGI5ZjU5OWZiYzJiYTM2ZTJiZjE1OTRiY2JiZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LDLDodVpTeT1ZuCSVWFheaBYoZhoNGykWO-dYNX3Zlw)
> 
> When I use Single instances and click on the Activate ALL command line, the following message appears:
> 
> ![2](https://private-user-images.githubusercontent.com/30214897/333852354-82ce60d7-8578-4330-a771-465796f4b70b.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTgyMTAsIm5iZiI6MTcxNjgxNzkxMCwicGF0aCI6Ii8zMDIxNDg5Ny8zMzM4NTIzNTQtODJjZTYwZDctODU3OC00MzMwLWE3NzEtNDY1Nzk2ZjRiNzBiLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEzNTE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNDdmYzhlODcyMTY2ZjNmMzg2ZjNlZGI1MzczNjQ4NzY2Zjc4OTZjNDg4NjdkODZkYWQ0ZTllMmIxMTNiOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SbuAf9nb6uLA8vCDKFzGUZItYBmW3IFMwBvB_Md0onw)
> 
> I hope you can assist in resolving it. Thank you

Uhh, that are some debug print statements that I forget to remove. You can ignore this messages. Take a look at the passivbot.log. And make Sure PBRun ist started.

You can join me on telegram for get support.

**Comment by sunhotblaze** [comment]
> > ![1](https://private-user-images.githubusercontent.com/30214897/333852347-7e56238f-ce92-43c3-8eba-4c2af7096c08.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTgyMTAsIm5iZiI6MTcxNjgxNzkxMCwicGF0aCI6Ii8zMDIxNDg5Ny8zMzM4NTIzNDctN2U1NjIzOGYtY2U5Mi00M2MzLThlYmEtNGMyYWY3MDk2YzA4LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEzNTE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNzg2NTFiYWMzMmI4NzRiMWRhMGE5MjUyMGMxZGJhOWY4ZGI5ZjU5OWZiYzJiYTM2ZTJiZjE1OTRiY2JiZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LDLDodVpTeT1ZuCSVWFheaBYoZhoNGykWO-dYNX3Zlw)
> > When I use Single instances and click on the Activate ALL command line, the following message appears:
> > ![2](https://private-user-images.githubusercontent.com/30214897/333852354-82ce60d7-8578-4330-a771-465796f4b70b.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTgyMTAsIm5iZiI6MTcxNjgxNzkxMCwicGF0aCI6Ii8zMDIxNDg5Ny8zMzM4NTIzNTQtODJjZTYwZDctODU3OC00MzMwLWE3NzEtNDY1Nzk2ZjRiNzBiLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEzNTE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNDdmYzhlODcyMTY2ZjNmMzg2ZjNlZGI1MzczNjQ4NzY2Zjc4OTZjNDg4NjdkODZkYWQ0ZTllMmIxMTNiOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SbuAf9nb6uLA8vCDKFzGUZItYBmW3IFMwBvB_Md0onw)
> > I hope you can assist in resolving it. Thank you
> 
> Uhh, that are some debug print statements that I forget to remove. You can ignore this messages. Take a look at the passivbot.log. And make Sure PBRun ist started.
> 
> You can join me on telegram for get support.

Thank you for your reply. I still haven't resolved the issue, and I have been trying to find the log file but haven't been able to find it

**Comment by sunhotblaze** [comment]
I have searched the data/logs/directory of pbgui and found no file logs for live execution. I have also searched the passivbot directory and found relevant logs. What should I do

**Comment by msei99** [comment]
closed
